### ISSUE TITLE
conda integration?

### ISSUE THREAD

**Issue by jmichel80** [HECBioSim/Longbow#74]
Hi James,

I was wondering if you have plans to distribute longbow via conda ? I'm thinking about ways a tool like longbow could be integrated in software dev projects and this would potentially solve some python portability headaches. 

Best wishes,

Julien

**Comment by jimboid** [comment]
Hi Julien,

I haven't had a proper look at conda yet, although I have noticed a shift towards conda as a packaging manager amongst other scientific codes. Longbow has no dependencies beyond standard python (all versions 2.6+) and some basic linux utilities (rsync and ssh) so I left the heavier packaging managers until somebody asked for them.

I will take a look at conda and see what I have to do, I'm guessing it will be fairly trivial to place Longbow into their package index due to its simplicity.

**Comment by jimboid** [comment]
After the discussion we had earlier on Skype, you are probably right that a conda install could work quite well for developers (especially biosimspace). I'm installing its build tools into a vm to see if it just works out of the box or not.

**Comment by jimboid** [comment]
Closing, old ticket. Can do pip install in conda environments so doesn't make sense to have another distribution mechanism
