### ISSUE TITLE
Using pre-existing queue scripts

### ISSUE THREAD

**Issue by jjuarez84** [HECBioSim/Longbow#77]
Hi James,

I was wondering if it would be possible to include the option of longbow using an already existing queue script instead of creating one on the fly. That way I would no need to struggle with longbow if I want to write non-standard commands in the queue script and I could still easily use it to transfer the files, launching the job, monitoring it and download the results when it is done. It would make my life a lot easier for what we are trying to do at the moment. Do you think that is a feature you would like to add?

Thanks a lot!

**Comment by jimboid** [comment]
I'm just trying to get a better understanding of what is currently missing from longbow. There are a number of options we can try here.

I could look at supporting this in Longbow, I would have to explore the effect it would have on the different modes longbow can be used in so that it doesn't cause other users problems/confusion.

If using Longbow like a library in your own code then you can implement this very quickly in your code, and I can show you how to do this (I know the dev docs on this subject are not quite good yet).

Does the script parameter not let you add in commands to the jobfile? or are you thinking of adding to the scheduler directives themselves? If it is scheduler features you need that are missing I can look into adding support for those (it is just a case of we just didn't know at the time how much users needed supported). 

Do you have a quick example of what you are trying to do in a submit script that you could share?

**Comment by jjuarez84** [comment]
Hi James,

The reason for needing this in my case is two fold: first it will allow me writing a queue script that makes more than one simulation in a single job (for example minimization + heating + equilibration). The second one is that way it gives me more freedom to handle customized cluster configurations (and I am thinking a little bit ahead here).

I am more than happy to implement longbow as a library in my code. I'll have a look to the dev docs and get back to you with more specific questions.

Thanks

**Comment by jimboid** [comment]
Is this still a requirement for you? I think I have stumbled across a very simple way to support this.

**Comment by jjuarez84** [comment]
Hi James,

I ended up integrating specific calls to Longbow functions inside my software to use pre-existing queue scripts, so It is not required by me at the moment. Still, if there is an easy way to support it I would encourage you to do it, because I think will increase Longbow's flexibility.

**Comment by jimboid** [comment]
Thanks for coming back on this. I'm glad you managed to find a solution that worked for you. I will still implement this as you say, it should be useful for others down the line.
